name: Auto Approve

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  approve:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, 'security')
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Approve and merge PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth status
          gh pr review ${{ github.event.pull_request.number }} --approve
          gh pr merge ${{ github.event.pull_request.number }} --merge
